# Generated by Django 6.0.2 on 2026-02-16 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PERDIDO', 'Buscando'), ('ENCONTRADO', 'Encontrado'), ('ENTREGADO', 'Entregado al dueño'), ('N/A', 'Ninguna / Otro')], default='N/A', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='objetos/')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='comunidad.objetoperdido')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comunidad.objetoperdido')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo / No aplica'), ('MEDICINA', 'Medicina'), ('ENFERMERIA', 'Enfermería'), ('ODONTOLOGIA', 'Odontología'), ('PSICOLOGIA', 'Psicología'), ('ADMIN_EMPRESAS', 'Administración de Empresas'), ('ADMIN_TURISMO', 'Adm. de Empresas Turísticas y Hoteleras'), ('NEGOCIOS', 'Negocios Internacionales'), ('CONTADURIA', 'Contaduría Pública'), ('ECONOMIA', 'Economía'), ('DERECHO', 'Derecho'), ('ANTROPOLOGIA', 'Antropología'), ('CINE', 'Cine y Audiovisuales'), ('BIOLOGIA', 'Biología'), ('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('ING_CIVIL', 'Ingeniería Civil'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_ELECTRONICA', 'Ingeniería Electrónica'), ('ING_AMBIENTAL', 'Ingeniería Ambiental y Sanitaria'), ('ING_AGRONOMICA', 'Ingeniería Agronómica'), ('ING_PESQUERA', 'Ingeniería Pesquera'), ('LIC_ARTES', 'Licenciatura en Artes'), ('LIC_CIENCIAS', 'Lic. en Ciencias Naturales y Edu. Ambiental'), ('LIC_CAMPESINA', 'Lic. en Educación Campesina y Rural'), ('LIC_INFANTIL', 'Licenciatura en Educación Infantil'), ('LIC_PREESCOLAR', 'Licenciatura en Educación Preescolar'), ('LIC_ETNOEDUCACION', 'Licenciatura en Etnoeducación'), ('LIC_LENGUAS', 'Lic. en Lenguas Extranjeras (Inglés)'), ('LIC_LITERATURA', 'Lic. en Literatura y Lengua Castellana'), ('LIC_MATEMATICAS', 'Licenciatura en Matemáticas'), ('LIC_TECNOLOGIA', 'Licenciatura en Tecnología')], max_length=100)),
                ('semestre', models.PositiveIntegerField(default=1)),
                ('es_verificado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('DUDAS', 'Dudas Académicas'), ('EVENTOS', 'Eventos y Fiestas'), ('CONFESIONES', 'Confesiones')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_anonimo', models.BooleanField(default=False)),
                ('carrera_filtro', models.CharField(blank=True, choices=[('ADMINISTRATIVO', 'Administrativo / No aplica'), ('MEDICINA', 'Medicina'), ('ENFERMERIA', 'Enfermería'), ('ODONTOLOGIA', 'Odontología'), ('PSICOLOGIA', 'Psicología'), ('ADMIN_EMPRESAS', 'Administración de Empresas'), ('ADMIN_TURISMO', 'Adm. de Empresas Turísticas y Hoteleras'), ('NEGOCIOS', 'Negocios Internacionales'), ('CONTADURIA', 'Contaduría Pública'), ('ECONOMIA', 'Economía'), ('DERECHO', 'Derecho'), ('ANTROPOLOGIA', 'Antropología'), ('CINE', 'Cine y Audiovisuales'), ('BIOLOGIA', 'Biología'), ('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('ING_CIVIL', 'Ingeniería Civil'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_ELECTRONICA', 'Ingeniería Electrónica'), ('ING_AMBIENTAL', 'Ingeniería Ambiental y Sanitaria'), ('ING_AGRONOMICA', 'Ingeniería Agronómica'), ('ING_PESQUERA', 'Ingeniería Pesquera'), ('LIC_ARTES', 'Licenciatura en Artes'), ('LIC_CIENCIAS', 'Lic. en Ciencias Naturales y Edu. Ambiental'), ('LIC_CAMPESINA', 'Lic. en Educación Campesina y Rural'), ('LIC_INFANTIL', 'Licenciatura en Educación Infantil'), ('LIC_PREESCOLAR', 'Licenciatura en Educación Preescolar'), ('LIC_ETNOEDUCACION', 'Licenciatura en Etnoeducación'), ('LIC_LENGUAS', 'Lic. en Lenguas Extranjeras (Inglés)'), ('LIC_LITERATURA', 'Lic. en Literatura y Lengua Castellana'), ('LIC_MATEMATICAS', 'Licenciatura en Matemáticas'), ('LIC_TECNOLOGIA', 'Licenciatura en Tecnología')], max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_foro', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_foro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comunidad.objetoperdido')),
            ],
            options={
                'unique_together': {('objeto', 'usuario')},
            },
        ),
    ]
